import { images } from "./images";

export const tabList = ["All", "Ongoing", "Completed"];

export const orders = [
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "completed",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "completed",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "completed",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
];

export const courier = [
  {
    courier_id: "kwik",
    courier_name: "Kwik",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1637024346/courier_images/kwik_ymsjvz.png",
    service_code: "kwik",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 109,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 9,
    ratings: 4.8,
    votes: 172,
    connected_account: false,
    rate_card_amount: 6377.78,
    rate_card_currency: "NGN",
    pickup_eta: "Within 2 Hours",
    pickup_eta_time: "2024-05-13 18:57:23",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Same day delivery",
    delivery_eta_time: "2024-05-13 19:57:23",
    info: null,
    currency: "NGN",
    vat: 408,
    total: 6377.78,
    tracking: {
      bars: 5,
      label: "Excellent",
    },
  },
  {
    courier_id: "darum",
    courier_name: "Darum NG",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1681942473/courier_images/darum_fyfgra.jpg",
    service_code: "darum",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 237,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 4,
    ratings: 4.7,
    votes: 46,
    connected_account: false,
    rate_card_amount: 6914.4,
    rate_card_currency: "NGN",
    pickup_eta: "Same day pickup",
    pickup_eta_time: "2024-05-13 23:57:23",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Next day delivery",
    delivery_eta_time: "2024-05-14 16:57:23",
    info: null,
    currency: "NGN",
    vat: 444,
    total: 6914.4,
    tracking: {
      bars: 3,
      label: "Average",
    },
  },
  {
    courier_id: "chowdeck",
    courier_name: "Relay (Chowdeck)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1713724533/courier_images/f6ff519b9ef671370dc845d9103a710f_zrm0no.jpg",
    service_code: "chowdeck",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 0,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 3,
    votes: 1,
    connected_account: false,
    rate_card_amount: 7681.92,
    rate_card_currency: "NGN",
    pickup_eta: "Within 30 minutes",
    pickup_eta_time: "2024-05-13 17:27:23",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Within 1 hour",
    delivery_eta_time: "2024-05-13 18:27:23",
    info: null,
    currency: "NGN",
    vat: 495,
    total: 7681.92,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "gigl",
    courier_name: "GIG Logistics",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1638640741/courier_images/gig_logo_wsxvwb.png",
    service_code: "gigl",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 53,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 9,
    ratings: 4.3,
    votes: 84,
    connected_account: false,
    rate_card_amount: 1773.68,
    rate_card_currency: "NGN",
    pickup_eta: "Within 48 Hours",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Within 48 hours",
    delivery_eta_time: "2024-05-15 20:44:17",
    info: null,
    currency: "NGN",
    vat: 99,
    total: 1773.68,
    tracking: {
      bars: 5,
      label: "Excellent",
    },
  },
  {
    courier_id: "fez-delivery_safelocker",
    courier_name: "Fez Safe Locker (Pick Up)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1694592734/courier_images/fez_logo_njmlnz.png",
    service_code: "fez-delivery",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 12,
    },
    service_type: "dropoff",
    waybill: false,
    is_cod_available: false,
    tracking_level: 6,
    ratings: 4.6,
    votes: 91,
    connected_account: false,
    rate_card_amount: 1416.96,
    rate_card_currency: "NGN",
    pickup_eta: "Within 48 Hours",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: null,
    pickup_station: {
      name: "Fez Safe Locker",
      address:
        "Ap Filling Station, 39 Oba Akran Ave, Ikeja, Lagos 101233, Lagos, Lagos, Nigeria",
      phone: null,
    },
    delivery_eta: "Dropoff in 24 Hours",
    delivery_eta_time: "2024-05-15 20:44:17",
    info: null,
    currency: "NGN",
    vat: 75,
    total: 1416.96,
    tracking: {
      bars: 3,
      label: "Average",
    },
  },
  {
    courier_id: "economy",
    courier_name: "Errandlr (Economy)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1681587684/courier_images/errandlr_logo_2_nxf4qt.png",
    service_code: "errandlr",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 9,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 4.3,
    votes: 72,
    connected_account: false,
    rate_card_amount: 1977.52,
    rate_card_currency: "NGN",
    pickup_eta: "Next day pickup",
    pickup_eta_time: "2024-05-14 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Next day delivery",
    delivery_eta_time: "2024-05-15 20:44:17",
    info: null,
    currency: "NGN",
    vat: 113,
    total: 1977.52,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "saver",
    courier_name: "UPS (Saver)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1698706665/courier_images/ups_logo_ujsjl1.png",
    service_code: "ups",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 8,
    },
    service_type: "pickup",
    waybill: true,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 4.2,
    votes: 5,
    connected_account: false,
    rate_card_amount: 2880.24,
    rate_card_currency: "NGN",
    pickup_eta: "Between 1 - 2 days",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Between 3 - 5 working days",
    delivery_eta_time: "2024-05-18 20:44:17",
    info: [
      "Download Label / waybill document from shipments page after shipment has been processed",
      "Attach Label / waybill document to your packaged items",
      "Items to be shippped must be wrapped or packaged before pickup",
    ],
    currency: "NGN",
    vat: 173,
    total: 2880.24,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "648913c40111d820891b91e3",
    courier_name: "Sendbox (Standard)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1637024201/courier_images/sendbox_ocoaqm.png",
    service_code: "sendbox",
    insurance: {
      code: "available",
      fee: 300,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 99,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 9,
    ratings: 4.4,
    votes: 61,
    connected_account: false,
    rate_card_amount: 3989.92,
    rate_card_currency: "NGN",
    pickup_eta: "Within 2 days",
    pickup_eta_time: "2024-05-13 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Within 8 days",
    delivery_eta_time: "2024-05-29 16:59:17",
    info: [
      "Download label from shipments page after shipment has been processed",
      "Attach label to your packaged items",
      "Items to be shippped must be wrapped or packaged before pickup",
    ],
    currency: "NGN",
    vat: 248,
    total: 3989.92,
    tracking: {
      bars: 5,
      label: "Excellent",
    },
  },
  {
    courier_id: "gavice",
    courier_name: "Gavice Logistics",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1715124877/courier_images/726f689c514aebe80abd7b15e02d3c2c_swj0kg.png",
    service_code: "gavice",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: null,
    },
    service_type: "dropoff",
    waybill: false,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 3,
    votes: 1,
    connected_account: false,
    rate_card_amount: 4213.52,
    rate_card_currency: "NGN",
    pickup_eta: "Within 2 Days",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: {
      name: "Balogun Trade-Fair",
      phone: "07065975827",
      address: "Balogun Trade-Fair, Trade Fair, Lagos, Nigeria",
    },
    pickup_station: {
      name: "Balogun Trade-Fair",
      phone: "07065975827",
      address: "Balogun Trade-Fair, Trade Fair, Lagos, Nigeria",
    },
    delivery_eta: "Between 4 - 5 working days",
    delivery_eta_time: "2024-05-18 20:44:17",
    info: null,
    currency: "NGN",
    vat: 263,
    total: 4213.52,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "on_demand",
    courier_name: "Errandlr",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1681587684/courier_images/errandlr_logo_2_nxf4qt.png",
    service_code: "errandlr",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 9,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 4.3,
    votes: 72,
    connected_account: false,
    rate_card_amount: 2759.6,
    rate_card_currency: "NGN",
    pickup_eta: "Within 3 Hours",
    pickup_eta_time: "2024-05-13 23:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Same day delivery",
    delivery_eta_time: "2024-05-14 01:44:17",
    info: null,
    currency: "NGN",
    vat: 165,
    total: 2759.6,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "speedaf-express",
    courier_name: "Speedaf Express",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1683363618/courier_images/speedaf_icon_zabfwj.png",
    service_code: "speedaf-express",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 54,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 6,
    ratings: 4,
    votes: 749,
    connected_account: false,
    rate_card_amount: 2312.4,
    rate_card_currency: "NGN",
    pickup_eta: "Within 24 - 48 Hours",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Between 3 - 5 working days",
    delivery_eta_time: "2024-05-18 20:44:17",
    info: [
      "Shipment placed after 3PM (GMT +1) will be processed to the next day",
      "Download waybill document from shipments page after shipment has been processed",
      "Attach waybill document to your packaged items",
      "Items to be shippped must be wrapped or packaged before pickup",
    ],
    currency: "NGN",
    vat: 135,
    total: 2312.4,
    tracking: {
      bars: 3,
      label: "Average",
    },
  },
  {
    courier_id: "skynet",
    courier_name: "Skynet NG",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1713724061/courier_images/058527feae542e3c9bf785430aa637e1_zbmhph.png",
    service_code: "skynet",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: null,
    },
    service_type: "pickup",
    waybill: true,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 3,
    votes: 1,
    connected_account: false,
    rate_card_amount: 3721.08,
    rate_card_currency: "NGN",
    pickup_eta: "Within 24 - 48 Hours",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Between 2 - 3 working days",
    delivery_eta_time: "2024-05-16 20:44:17",
    info: [
      "Download Label / waybill document from shipments page after shipment has been processed",
      "Attach Label / waybill document to your packaged items",
      "Items to be shippped must be wrapped or packaged before pickup",
    ],
    currency: "NGN",
    vat: 229.5,
    total: 3721.08,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "standard",
    courier_name: "UPS (Standard)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1698706665/courier_images/ups_logo_ujsjl1.png",
    service_code: "ups",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 8,
    },
    service_type: "pickup",
    waybill: true,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 4.2,
    votes: 5,
    connected_account: false,
    rate_card_amount: 2548.48,
    rate_card_currency: "NGN",
    pickup_eta: "Between 2 - 3 days",
    pickup_eta_time: "2024-05-16 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Between 5 - 7 working days",
    delivery_eta_time: "2024-05-20 20:44:17",
    info: [
      "Download Label / waybill document from shipments page after shipment has been processed",
      "Attach Label / waybill document to your packaged items",
      "Items to be shippped must be wrapped or packaged before pickup",
    ],
    currency: "NGN",
    vat: 151,
    total: 2548.48,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
  {
    courier_id: "fez-delivery",
    courier_name: "Fez delivery",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1694592734/courier_images/fez_logo_njmlnz.png",
    service_code: "fez-delivery",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 12,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 6,
    ratings: 4.6,
    votes: 91,
    connected_account: false,
    rate_card_amount: 3654,
    rate_card_currency: "NGN",
    pickup_eta: "Within 48 Hours",
    pickup_eta_time: "2024-05-15 20:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Between 2 - 4 working days",
    delivery_eta_time: "2024-05-17 20:44:17",
    info: null,
    currency: "NGN",
    vat: 225,
    total: 3654,
    tracking: {
      bars: 3,
      label: "Average",
    },
  },
  {
    courier_id: "dellyman",
    courier_name: "Dellyman",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1697995461/courier_images/dellyman_logo_ckd6z8.png",
    service_code: "dellyman",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 36,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 4.8,
    votes: 31,
    connected_account: false,
    rate_card_amount: 2312.4,
    rate_card_currency: "NGN",
    pickup_eta: "Same day pickup",
    pickup_eta_time: "2024-05-14 03:44:17",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Next day delivery",
    delivery_eta_time: "2024-05-15 20:44:17",
    info: null,
    currency: "NGN",
    vat: 135,
    total: 2312.4,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
];

export const places = [
  {
    label: "Select address (Default)",
    value: "0",
  },
  {
    label: "Ikeja, Lagos, Nigeria",
    value: "ChIJmTkq-iiSOxAR8KG73UsyqNc",
  },
  {
    label: "Lekki, Lagos, Nigeria",
    value: "ChIJZ0PH9V33OxARSs3B1vl9fmo",
  },
  {
    label: "Magodo GRA Phase II, Ikosi Ketu, Ikeja 105102, Lagos, Nigeria",
    value: "ChIJt8m3maiTOxAR_U_E23HeMIY",
  },
  {
    label: "Ketu, Ikeja 105102, Lagos, Nigeria",
    value: "ChIJ44YZ1_6SOxARliSZC8Qx8hU",
  },
  {
    label: "Surulere, Ikeja, Lagos, Nigeria",
    value: "ChIJfc4mrxqMOxARo-GNtZjWL00",
  },
  {
    label: "Olowora, Ojodu Berger 105102, Lagos, Nigeria",
    value: "ChIJTVYf6fPROxAR4eMdwPZMNRU",
  },
];

export const categories = [
  { label: "Select category", value: "0" },
  { label: "Accessories", value: "1" },
  { label: "Gadgets and Electronics", value: "2" },
  { label: "Food", value: "3" },
  { label: "Groceries", value: "4" },
  { label: "Machineries", value: "5" },
  { label: "Medical Supplies", value: "6" },
  { label: "Fashion", value: "7" },
  { label: "Furniture", value: "8" },
];
