import { images } from "./images";

export const tabList = ["All", "Ongoing", "Completed"];

export const orders = [
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "completed",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "completed",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "completed",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "GIG Logistics",
      logo: images["m-logo"],
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "SpeedAf",
      logo: "",
      location: "Lagos",
    },
  },
  {
    userId: "",
    username: "",
    deliveryId: "XSJ17HGR0ET",
    sender: "Sender A",
    receiver: "Receiver A",
    pickup: "Ikeja",
    deliverTo: "Lekki",
    status: "ongoing",
    timeStamp: "",
    price: "2,000",
    placeId: "",
    dispatcher: {
      name: "ABC Transport",
      logo: "",
      location: "Lagos",
    },
  },
];

export const courier = [
  {
    courier_id: "kwik",
    courier_name: "Kwik",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1637024346/courier_images/kwik_ymsjvz.png",
    service_code: "kwik",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 109,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 9,
    ratings: 4.8,
    votes: 172,
    connected_account: false,
    rate_card_amount: 6377.78,
    rate_card_currency: "NGN",
    pickup_eta: "Within 2 Hours",
    pickup_eta_time: "2024-05-13 18:57:23",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Same day delivery",
    delivery_eta_time: "2024-05-13 19:57:23",
    info: null,
    currency: "NGN",
    vat: 408,
    total: 6377.78,
    tracking: {
      bars: 5,
      label: "Excellent",
    },
  },
  {
    courier_id: "darum",
    courier_name: "Darum NG",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1681942473/courier_images/darum_fyfgra.jpg",
    service_code: "darum",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 237,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 4,
    ratings: 4.7,
    votes: 46,
    connected_account: false,
    rate_card_amount: 6914.4,
    rate_card_currency: "NGN",
    pickup_eta: "Same day pickup",
    pickup_eta_time: "2024-05-13 23:57:23",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Next day delivery",
    delivery_eta_time: "2024-05-14 16:57:23",
    info: null,
    currency: "NGN",
    vat: 444,
    total: 6914.4,
    tracking: {
      bars: 3,
      label: "Average",
    },
  },
  {
    courier_id: "chowdeck",
    courier_name: "Relay (Chowdeck)",
    courier_image:
      "https://res.cloudinary.com/delivry/image/upload/v1713724533/courier_images/f6ff519b9ef671370dc845d9103a710f_zrm0no.jpg",
    service_code: "chowdeck",
    insurance: {
      code: "not available",
      fee: 0,
    },
    discount: {
      percentage: 20,
      symbol: "%",
      discounted: 0,
    },
    service_type: "pickup",
    waybill: false,
    is_cod_available: false,
    tracking_level: 7,
    ratings: 3,
    votes: 1,
    connected_account: false,
    rate_card_amount: 7681.92,
    rate_card_currency: "NGN",
    pickup_eta: "Within 30 minutes",
    pickup_eta_time: "2024-05-13 17:27:23",
    dropoff_station: null,
    pickup_station: null,
    delivery_eta: "Within 1 hour",
    delivery_eta_time: "2024-05-13 18:27:23",
    info: null,
    currency: "NGN",
    vat: 495,
    total: 7681.92,
    tracking: {
      bars: 4,
      label: "Good",
    },
  },
];

export const places = [
  {
    label: "Select address (Default)",
    value: "0",
  },
  {
    label: "Ikeja, Lagos, Nigeria",
    value: "ChIJmTkq-iiSOxAR8KG73UsyqNc",
  },
  {
    label: "Lekki, Lagos, Nigeria",
    value: "ChIJZ0PH9V33OxARSs3B1vl9fmo",
  },
  {
    label: "Magodo GRA Phase II, Ikosi Ketu, Ikeja 105102, Lagos, Nigeria",
    value: "ChIJt8m3maiTOxAR_U_E23HeMIY",
  },
  {
    label: "Ketu, Ikeja 105102, Lagos, Nigeria",
    value: "ChIJ44YZ1_6SOxARliSZC8Qx8hU",
  },
  {
    label: "Surulere, Ikeja, Lagos, Nigeria",
    value: "ChIJfc4mrxqMOxARo-GNtZjWL00",
  },
  {
    label: "Olowora, Ojodu Berger 105102, Lagos, Nigeria",
    value: "ChIJTVYf6fPROxAR4eMdwPZMNRU",
  },
];

export const categories = [
  { label: "Select category", value: "0" },
  { label: "Accessories", value: "1" },
  { label: "Gadgets and Electronics", value: "2" },
  { label: "Food", value: "3" },
  { label: "Groceries", value: "4" },
  { label: "Machineries", value: "5" },
  { label: "Medical Supplies", value: "6" },
  { label: "Fashion", value: "7" },
  { label: "Furniture", value: "8" },
];
